// Generates the sidebar's vector wordmark. Run from the repository root:
// swift scripts/render-sidebar-wordmark.swift
import AppKit
import CoreText

func number(_ value: CGFloat) -> String {
    String(format: "%.4f", locale: Locale(identifier: "en_US_POSIX"), Double(value))
        .replacingOccurrences(of: #"\.?0+$"#, with: "", options: .regularExpression)
}

func svgPath(_ path: CGPath) -> String {
    var commands: [String] = []
    func point(_ p: CGPoint) -> String { "\(number(p.x)) \(number(p.y))" }
    path.applyWithBlock { element in
        let points = element.pointee.points
        switch element.pointee.type {
        case .moveToPoint: commands.append("M\(point(points[0]))")
        case .addLineToPoint: commands.append("L\(point(points[0]))")
        case .addQuadCurveToPoint: commands.append("Q\(point(points[0])) \(point(points[1]))")
        case .addCurveToPoint: commands.append("C\(point(points[0])) \(point(points[1])) \(point(points[2]))")
        case .closeSubpath: commands.append("Z")
        @unknown default: fatalError("Unsupported glyph path element")
        }
    }
    return commands.joined(separator: " ")
}

let font = NSFont.systemFont(ofSize: 18, weight: .medium)
let ctFont = font as CTFont
let line = CTLineCreateWithAttributedString(NSAttributedString(string: "airdraft", attributes: [.font: font]))
let lettering = CGMutablePath()
for run in CTLineGetGlyphRuns(line) as! [CTRun] {
    let count = CTRunGetGlyphCount(run)
    var glyphs = [CGGlyph](repeating: 0, count: count)
    var positions = [CGPoint](repeating: .zero, count: count)
    CTRunGetGlyphs(run, CFRange(location: 0, length: count), &glyphs)
    CTRunGetPositions(run, CFRange(location: 0, length: count), &positions)
    for index in 0..<count {
        guard let path = CTFontCreatePathForGlyph(ctFont, glyphs[index], nil) else {
            fatalError("Missing wordmark glyph")
        }
        lettering.addPath(path, transform: CGAffineTransform(translationX: positions[index].x, y: positions[index].y))
    }
}

// SF's capital I is a straight stem. Its actual outline sets the icon's weight.
var stemCharacter = UniChar(73)
var stemGlyph = CGGlyph()
precondition(CTFontGetGlyphsForCharacters(ctFont, &stemCharacter, &stemGlyph, 1))
let stroke = CTFontCreatePathForGlyph(ctFont, stemGlyph, nil)!.boundingBoxOfPath.width
let canvasHeight: CGFloat = 24
let capsuleHeight: CGFloat = 20
let iconScale = capsuleHeight / 364
let capsuleWidth = 744 * iconScale
let bounds = lettering.boundingBoxOfPath
let textX = capsuleWidth + 8
let canvasWidth = ceil(textX + bounds.width)
var textTransform = CGAffineTransform(a: 1, b: 0, c: 0, d: -1,
                                     tx: textX - bounds.minX,
                                     ty: canvasHeight / 2 + bounds.midY)
let textPath = lettering.copy(using: &textTransform)!

// Keep the app icon's five waveform levels and its separated text caret.
let levels: [CGFloat] = [0.36, 0.66, 1, 0.72, 0.48]
let groupWidth: CGFloat = 6 * 38 + 5 * 30 + 20
let groupX = (capsuleWidth - groupWidth * iconScale) / 2
var bars: [String] = []
for index in 0..<6 {
    let x = groupX + (19 + CGFloat(index) * 68 + (index == 5 ? 20 : 0)) * iconScale
    let height = (index == 5 ? 208 : 190 * levels[index]) * iconScale
    let top = (canvasHeight - height + stroke) / 2
    let bottom = (canvasHeight + height - stroke) / 2
    bars.append("M\(number(x)) \(number(top)) V\(number(bottom))")
}

let svg = """
<svg xmlns="http://www.w3.org/2000/svg" width="\(number(canvasWidth))" height="24" viewBox="0 0 \(number(canvasWidth)) 24">
  <title>Airdraft</title>
  <!-- Generated by scripts/render-sidebar-wordmark.swift. Lettering is outlined SF Pro Medium, 18 pt. -->
  <g fill="none" stroke="#000" stroke-width="\(number(stroke))" stroke-linecap="round" stroke-linejoin="round">
    <rect x="\(number(stroke / 2))" y="\(number((canvasHeight - capsuleHeight + stroke) / 2))" width="\(number(capsuleWidth - stroke))" height="\(number(capsuleHeight - stroke))" rx="\(number((capsuleHeight - stroke) / 2))"/>
    <path d="\(bars.joined(separator: " "))"/>
  </g>
  <path fill="#000" d="\(svgPath(textPath))"/>
</svg>

"""
let output = URL(fileURLWithPath: "Sources/App/Assets.xcassets/SidebarWordmark.imageset/wordmark.svg")
try FileManager.default.createDirectory(at: output.deletingLastPathComponent(), withIntermediateDirectories: true)
try svg.write(to: output, atomically: true, encoding: .utf8)
print("Wrote \(output.path): \(number(canvasWidth)) × 24 pt, \(number(stroke)) pt stroke")
